name: SingleAgentRunner
kwargs:
  experiment_manager:
    name: Experiment
    kwargs:
      name: episodic_sandbox
      save_dir: experiment
      saving_schedule:
        name: PeriodicSchedule
        kwargs:
          off_value: false
          on_value: true
          period: 1000000
  train_steps: 150000
  max_steps_per_episode: 500  # episodic
  #train_phase_steps: 2000 # reset-free
  test_frequency: 1000
  test_episodes: 2
  test_max_steps: 20
  test_random_goals: true
  seed: 0
  stack_size: 1
  eval_every: false
  early_terminal: true
  send_truncation: false
  env_fn:
    name: minigrid_envs
    kwargs:
      env_name: MiniGrid-Hallway-v1
      eval_max_steps: 100
      local_vis_period: 2000
      reset_free: false  # episodic
      symbolic: true
      train_max_steps: 500  # episodic
      video_period: 100
      vis_frequency: 2000
      render_mode: human
  agent:
    name: GCResetFree
    kwargs:
      base_agent:
        kwargs:
          batch_size: 128
          device: cpu
          discount_rate: 0.95
          epsilon_schedule:
            #name: ConstantSchedule
            #kwargs:
            #  value: 0.0
            name: LinearSchedule
            kwargs:
              end_value: 0.1
              init_value: 1.0
              steps: 20000
          loss_fn:
            name: MSELoss
          optimizer_fn:
            name: Adam
            kwargs:
              lr: 0.0003
          min_replay_history: -1
          compute_success_probability: false
          representation_net:
            name: ConvNetwork
            kwargs:
              channels: [16, 16, 16]
              paddings: 1
              kernel_sizes: 3
              mlp_layers: [16]
          target_net_update_schedule:
            name: PeriodicSchedule
            kwargs:
              off_value: false
              on_value: true
              period: 500
        name: GoalConditionedDQNAgent
      novelty_bonus: true
      goal_generator:
        #name: FBGoalGenerator  # RISC
        name: OmniGoalGenerator
        kwargs:
          debug: true
          vis_frequency: 50
          weights: [1, 1, 1, 1]
          max_visitations: 10
          use_success_prob: false
          oracle: true
      phase_step_limit: [5, 1, 20]
      goal_switcher:
        #name: BasicGoalSwitcher
        #name: SuccessProbabilityGoalSwitcher  # reset-free
        name: TimeoutGoalSwitcher
        kwargs:
          #novel_threshold: 1
          #familiar_threshold: 2
          switching_probability: 0.45
          oracle: false
      replay_buffer:
        name: CountsReplayBuffer
        #name: HERReplayBuffer  # HER
        kwargs:
          capacity: 100000
          #her_batch_size: 16  # HER
      separate_agents: false
      local_visitation_vis_frequency: 2000
      oracle: false
      directions: [forward, teleport_backward, lateral]
  loggers:
  #- name: WandbLogger
  #  kwargs:
  #    name: episodic_sandbox
  #    project: Debug
  #    resume: allow
  #    start_method: fork
