name: SingleAgentRunner
kwargs:
  experiment_manager:
    name: Experiment
    kwargs:
      name: &run_name MiniHack_SIERL
      save_dir: experiment
      saving_schedule:
        name: PeriodicSchedule
        kwargs:
          off_value: false
          on_value: true
          period: 1000000
  train_steps: 1000000
  max_steps_per_episode: &train_steps 600  # episodic
  test_max_steps: &test_steps 80
  test_frequency: 1000
  test_episodes: 10
  # train_random_goals: true
  test_random_goals: true
  seed: 0
  stack_size: 1
  eval_every: false
  early_terminal: true
  send_truncation: false
  env_fn:
    name: minihack_envs
    kwargs:
      env_name: MiniHack-Boxoban-Unfiltered-v0
      train_max_steps: *train_steps  # episodic
      eval_max_steps: *test_steps
      #step_reward: &step_reward -1
      #goal_reward: &goal_reward 0
      # novelty_bonus: 0.0
      # local_vis_period: 2000
      # video_period: 50  # episodes
      # video_length: *train_steps
      # vis_frequency: 2000
      # render_mode: human
  agent:
    name: GCResetFree
    kwargs:
      base_agent:
        name: GoalConditionedDQNAgent
        kwargs:
          batch_size: 128
          device: cpu
          discount_rate: &discount_rate 0.95
          epsilon_schedule:
            #name: ConstantSchedule
            #kwargs:
            #  value: 0.0
            name: LinearSchedule
            kwargs:
              end_value: 0.1
              init_value: 1.0
              steps: 20000
          loss_fn:
            name: MSELoss
          optimizer_fn:
            name: Adam
            kwargs:
              lr: 0.0003
          min_replay_history: 128
          compute_success_probability: false
          representation_net:
            name: ConvNetwork
            kwargs:
              channels: [16, 16, 16]
              paddings: 1
              kernel_sizes: 3
              mlp_layers: [16]
          target_net_update_schedule:
            name: PeriodicSchedule
            kwargs:
              off_value: false
              on_value: true
              period: *train_steps
          use_oracle: false
      goal_generator:
        name: OmniGoalGenerator
        kwargs:
          # debug: true
          vis_frequency: 0
          weights: [1.5, 0, 1, 0.5]
          frontier_proportion: 1.0
          max_familiarity: 0.9
          use_success_prob: false
          use_oracle: false
          # random_selection: true
          temperature_schedule:
            name: ConstantSchedule
            kwargs:
              value: 0.5
          sierl_prob_schedule:
            name: ConstantSchedule
            kwargs:
              value: 1.0
            # name: LinearSchedule
            # kwargs:
            #   init_value: 0.75
            #   end_value: 0.05
            #   steps: 500  # episodes
      goal_switcher:
        name: TimeoutGoalSwitcher
        kwargs:
          switching_probability: 0.7
          use_oracle: false
      replay_buffer:
        name: CountsReplayBuffer
        # name: HERReplayBuffer  # HER
        kwargs:
          capacity: 100000
          gamma: 0.5
          # her_ratio: 0.5  # HER
      separate_agents: false
      # log_frequency: 1
      local_visitation_vis_frequency: 2000
      directions: [forward, teleport_backward, lateral]
      phase_step_limit: [2, 1, 747]
  loggers:
    - name: WandbLogger
      kwargs:
        name: *run_name
        project: Experiments
        resume: allow
        start_method: fork
