name: ResetFreeRunner
kwargs:
  experiment_manager:
    name: Experiment
    kwargs:
      name: FourRooms_FLBL_1.0_1.0_1.0_1.0
      save_dir: experiment
      saving_schedule:
        name: PeriodicSchedule
        kwargs:
          off_value: false
          on_value: true
          period: 1000000
  #train_steps: 100000
  train_steps: 300000
  test_frequency: 1000
  test_episodes: 10
  test_max_steps: 100
  #test_max_steps: 150
  seed: 0
  stack_size: 1
  eval_every: false
  early_terminal: true
  send_truncation: false
  env_fn:
    name: minigrid_envs
    kwargs:
      env_name: MiniGrid-FourRooms-v1
      eval_max_steps: 100
      local_vis_period: 2000
      reset_free: true  # reset-free
      #reset_free: false  # episodic
      symbolic: true
      #train_max_steps: 100000  # reset-free
      train_max_steps: 300000  # reset-free
      #train_max_steps: 30  # episodic
      video_period: 1000
      vis_frequency: 2000
      #render_mode: human
  agent:
    name: GCResetFree
    kwargs:
      base_agent:
        kwargs:
          batch_size: 128
          device: cpu
          discount_rate: 0.95
          epsilon_schedule:
            name: LinearSchedule
            kwargs:
              end_value: 0.1
              init_value: 1.0
              steps: 10000
          loss_fn:
            name: MSELoss
          min_replay_history: 512
          replay_buffer:
            name: CircularReplayBuffer
            kwargs:
             capacity: 100000
          representation_net:
            name: ConvNetwork  # RISC
            kwargs:
              channels: [16, 16, 16]
              paddings: 1
              kernel_sizes: 3
              mlp_layers: [16]
            #name: MLPNetwork
            #kwargs:
            #  hidden_units: [256, 256, 64]
          target_net_update_schedule:
            name: PeriodicSchedule
            kwargs:
              off_value: false
              on_value: true
              period: 500
        name: GoalConditionedDQNAgent
      goal_generator:
        name: OmniGoalGenerator
        #name: FBGoalGenerator  # RISC
      goal_switcher:
        name: SuccessProbabilityGoalSwitcher  # reset-free
        #name: BasicGoalSwitcher  # episodic
      phase_step_limit: 100
      replay_buffer:
        #name: CircularReplayBuffer
        name: CountsReplayBuffer
        #name: HERReplayBuffer  # HER
        kwargs:
          capacity: 100000
          #capacity: 500000
          #her_batch_size: 64  # HER
      separate_agents: true
      weights: [1, 1, 1, 1]
      directions: [forward, lateral, backward, lateral]
  loggers:
  - name: WandbLogger
    kwargs:
      name: FourRooms_FLBL_1.0_1.0_1.0_1.0
      project: Debug
      resume: allow
      start_method: fork
